### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by b1ek** [gelstudios/gitfiti#102]
Occurs on both windows and linux
```
$ python3 ./gitfiti.py

          _ __  _____ __  _
   ____ _(_) /_/ __(_) /_(_)
  / __ `/ / __/ /_/ / __/ /
 / /_/ / / /_/ __/ / /_/ /
 \__, /_/\__/_/ /_/\__/_/
/____/

Enter GitHub URL (leave blank to use https://github.com/):
Enter your GitHub username: b1ek
Traceback (most recent call last):
  File "/mnt/c/Users/blek/Documents/gitfiti/./gitfiti.py", line 507, in <module>
    main()
  File "/mnt/c/Users/blek/Documents/gitfiti/./gitfiti.py", line 438, in main
    max_daily_commits = find_max_daily_commits(contributions_calendar)
  File "/mnt/c/Users/blek/Documents/gitfiti/./gitfiti.py", line 308, in find_max_daily_commits
    return max(daily_counts)
ValueError: max() arg is an empty sequence
```

**Comment by b1ek** [comment]
See #103

**Comment by PareshChawla** [comment]
Simply put default=0 in return max on line no 308
like this:
def find_max_daily_commits(contributions_calendar):
    """finds the highest number of commits in one day"""
    daily_counts = parse_contributions_calendar(contributions_calendar)
    return max(daily_counts, default=0)

**Comment by 607011** [comment]
Problem is line 299. Change `'data-count='` to `'data-value='` and everything will be fine, @gelstudios

**Comment by gelstudios** [comment]
@607011 looks like 'data-value=' was removed from the svg (on github.com at least), see #105
